#!/usr/bin/env bash

read string

string_length=${#string}

function printComments {
    echo $(printf '%*s' $((string_length=string_length+9)) | tr ' ' '#')
}

printComments
echo "#### $string ####"
printComments
