#!/usr/bin/env bash
#
# wat if we have more than one template?

temporary=$(mktemp) || exit 1
_e='echo -e'
option=
string=
size=0

function config {
    o='s/vhc:([a-z,]*);(.*)$/'
    option=$($_e "$1"|sed -r "${o}"'\1/')
    string=$($_e "$1"|sed -r "${o}"'\2/')
}

while read -r string
do  [[  "${string:0:4}" == "vhc:" ]] && config "${string}"
    [[  ${#string} -gt  ${size}   ]] &&   size=${#string}
    $_e "${string}" >> "${temporary}"
done

case "${option,,}" in
    sides)               adjust=2; corner=('⎣'   '⎦' '⎡'  '⎤'); lines=(' ' ' ⎥' ' ' '⎢ ' );;
    prettybox)           adjust=2; corner=('└'   '┘' '┌'  '┐'); lines=('─' ' │' '─' '│ ' );;
    quotes)              adjust=2; corner=('"'   ' ' ' '  '"'); lines=(' ' ' '  ' ' ' '  );;
    ccomment)            adjust=2; corner=(' */' ' ' '/*' ' '); lines=(' ' ' '  ' ' ' * ');;
    lcomment)            adjust=2; corner=('//'  ' ' '//' ' '); lines=(' ' ' '  ' ' '// ');;
    box)                 adjust=2; corner=('+'   '+' '+'  '+'); lines=('-' ' |' '-' '| ' );;
    star|stars|asterisk) adjust=2; corner=('*'   '*' '*'  '*'); lines=('*' ' *' '*' '* ' );;
    ernjs|ernando|*)     adjust=8; corner=('#'   '#' '#'  '#'); lines=('#' ' ####' '#' '#### ')
esac

function str_repeat {
    n=$1
    while [[ $n -gt 0 ]]
    do  $_e  -n "$2"
        n=$(( n - 1 ))
    done
}

function line {
    [ $# -eq 1 ] \
        && str_repeat  "$((size + adjust))" "$1" \
        && exit

    $_e "${corner[$1]}$(line "${lines[$1]}")${corner[$2]}"
}

function line_top {
    line 0 1
}

function line_bottom {
    line 2 3
}

trap  line_top \
EXIT; line_bottom

while read -r string
do  spacing=$(printf '%*s' $((size - ${#string})))
    $_e "${lines[3]}${string}${spacing}${lines[1]}"
done  < "${temporary}"
rm      "${temporary}"
