#!/usr/bin/env bash

# wat if we have more than one line?
while read string
do string_length=$((${#string} + 10))

    echo $(printf '%*s' $string_length | tr ' ' '#')
    echo "#### $string ####"
    echo $(printf '%*s' $string_length | tr ' ' '#')
done
